#!/bin/bash

# Create the tech logos directory
mkdir -p public/images/tech

echo "📦 Technology Logos Setup"
echo "========================"
echo ""
echo "This script will help you download technology logos."
echo ""
echo "Option 1: Download from Simple Icons (recommended)"
echo "Visit: https://simpleicons.org/"
echo "Search for each technology and download the SVG"
echo ""
echo "Option 2: Use the Simple Icons npm package"
echo "Run: npm install simple-icons"
echo "Then copy icons from: node_modules/simple-icons/icons/"
echo ""
echo "Required logos (${1:-60}+ files):"
echo "- Languages: typescript, javascript, python, swift, react, etc."
echo "- Cloud: aws, azure, gcp, vercel, docker, kubernetes"
echo "- Databases: postgresql, mongodb, redis, supabase, firebase"
echo "- Analytics: mixpanel, amplitude, segment, posthog, datadog"
echo "- Design: figma, framer, storybook, adobexd"
echo "- Dev Tools: git, github, vscode, linear, jira, notion"
echo "- Testing: jest, cypress, playwright, postman"
echo "- Mobile: expo, xcode, swiftui, testflight"
echo ""
echo "💡 Quick Setup:"
echo "1. npm install simple-icons"
echo "2. Run the copy-tech-logos.js script to batch copy"
echo ""
echo "Target directory: public/images/tech/"
echo ""
echo "See TECH_LOGOS_SETUP.md for the complete list and instructions."
